# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlieeOEyCdgGnavJpgrYK4H5DmxuN-D6
"""

import random

def calculate_risk_score(user_type):
    # Simulated logic based on user_type
    base_scores = {
        "Teen": random.randint(50, 90),
        "Parent": random.randint(30, 70),
        "Senior": random.randint(60, 95)
    }
    return base_scores.get(user_type, random.randint(40, 80))